- hosts: all
  remote_user: ec2-user
  become: yes
  tasks:
  
   - name: Apache installation
     yum: 
      name: httpd
      state: installed

   - name: start Apache
     service: 
      name: httpd
      state: started
       
   - name: copy files
     copy: 
      src: ./index.html
      dest: /var/www/html/index.html
