- hosts: all
  remote_user: ec2-user
  become: True
  tasks:
    - name: Install nginx
      yum:
       name: nginx
       state: installed
    
    - name: start nginx
      service:
        name: nginx
        state: started 

    - name:
      copy:
       src: ./index.html
       dest: /usr/share/nginx/html/index.html

